language: c

script:
- mkdir build
- cd build
- cmake ..
- make

notifications:
  slack:
    secure:
     Un3kjm4XoIZ167VlbTzDiHCxJ2GnhJZKLda2Ru9oKKwEGOLTtYl8bvCQ5VI6RYDmLZJtcNouhxPHx8o+iinSTlpyvDEv7R8kZAMoPQqBiO524KKSpNzHcjlQLNi3A5y/+692c5EZY2qFgewpwNDijH2jS0vjwgyw0zCMRAhAAAyss4ppaS8rGRuk8JlQ+78mcvyxDVIWeT+dZM0iVMJXGL29wxzribc3OK1AktiQtMCoIyZjznkVhS89noDxAENzYAHA2JX6fr2CZ/uaM0F6SX52AH0lEm31CKV77nSddzbhF0mP764aBfiB/O7rSMdqta5mskkIPaQsqGamdMotBMcko+VJzdThUq6piMKYS8izy2EDlYpxDP1DVlTaPfRgzaYQa2jItJL+/aJqByeDqWCx8eKdHm5dPGTtXODA7+hUVArE4BY38EZIboLZ1K5sP7feAg0TtV/pzvxt2ao119SJaedWsC3QCPCNM17zS8QLmKqLdhWOmTqBRbL6qIEXUOWMvhR7ewwes11cTTTWNPcQYdp+hiYUFsKin7I6m3GuCemZspL0pSQ3VVDzcItNUFVr4+ZdHnY3ghUOXbdn4glSBDSnDfTILF2x/OrPP0eyaKDKFprcnLorGEUj1PF7lYS4RRe7a/7nIpOFSsf8vZC7f1ucD/1JlvFGE3PPL2w=
  email: false
